### ISSUE TITLE
Improve the header

### ISSUE THREAD

**Issue by combatantash** [combatantash/catalogue-page#1]
Make the header bit attractive

**Comment by vedamruta** [comment]
Hi, I'll try to make the header "Product Catalogue Page" attractive to the best of my capabilities. :)

**Comment by combatantash** [comment]
Assigned to you @vedamruta 
Good luck 👍

**Comment by Ishikasaraf20** [comment]
hey @combatantash can you assign this issue to me i can work on it

**Comment by singhkaran202** [comment]
Hello @vedamruta, I'd love to work on this if that's OK.
Could you please assign me this?

**Comment by combatantash** [comment]
@vedamruta please upload the screenshot of the changes you have done along with the comment explaining it. That i can merge the PR

**Comment by vedamruta** [comment]
@singhkaran202 Sorry, I checked your comment now.
