### ISSUE TITLE
Decrease the speed of marquee element

### ISSUE THREAD

**Issue by combatantash** [combatantash/catalogue-page#2]

**Comment by vedamruta** [comment]
I would like to fix the Marquee Element speed :)
Please assign me to do so.

**Comment by combatantash** [comment]
Assigned to you @vedamruta 
You can also see what other changes you can do and then you can create a issue regarding it and then i'l assign the same issue to you.

**Comment by vedamruta** [comment]
Sure, I have made 2 PRs for the same :)
Thank you :)

**Comment by combatantash** [comment]
@vedamruta please upload the screenshot of the changes you have done along with the comment. that i can merge the PR
